set(LIGHTCLIENT_SOURCES_DIR ${CMAKE_CURRENT_LIST_DIR})

set(LIGHTCLIENT_SOURCES
    ${LIGHTCLIENT_SOURCES_DIR}/lightclient.c
    ${LIGHTCLIENT_SOURCES_DIR}/object_security.c
    ${LIGHTCLIENT_SOURCES_DIR}/object_device.c
    ${LIGHTCLIENT_SOURCES_DIR}/object_server.c
    ${LIGHTCLIENT_SOURCES_DIR}/object_test.c
)
